### PR TITLE
fix: multicodec hex conversion

### LINKED ISSUE #21: Codec showing varint instead of code
for reference:

https://cid.ipfs.io/#baguqeeranycvebnhdwjwaimaylo2lon5h22ueqdto74e5wnfnm7rspq4or7q

shows code is `0xa902` where the actual JSON code is `0x0129`. The former is the varint encoding of the latter, but misleading because it's the wrong code and isn't decoded

### PR DESCRIPTION
**Pull request by dennis-tra**
Fixes #21

### CODE REVIEW

**Review by lidel — CHANGES_REQUESTED** [review]
@dennis-tra  thank you for tackling this! Unfortunately something is still fishy:

The codec of `baguqeeranycvebnhdwjwaimaylo2lon5h22ueqdto74e5wnfnm7rspq4or7q` is `dag-json`, so hex should be `0x0129`  but it shows as `0xa902`

My understanding is that we want to output values matching in the "code" column of https://github.com/multiformats/multicodec/blob/master/table.csv

Perhaps you could switch this to use `multicodec.getNumber` function which was recently fixed in https://github.com/multiformats/js-multicodec/pull/65 ?

Mind updating this PR to something like:

```diff
+ const multicodecLib = require('multicodec')

-      code: '0x' + mutlicodecVarintTable[cid.codec].toString('hex')
+      code: '0x' + multicodecLib.getNumber(cid.codec).toString(16)


```

**Comment by dennis-tra** [comment]
Hi @lidel,

sorry for the premature "fix" I tested it with only one other CID (don't remember which it was) and saw the correct code. I have the same understanding regarding the "code" column.

Anyways, I did the changes as you suggested and it shows `dag-json` and `0x129` for your CID. Just note: it does not show exactly the "code" column - compare `0x129` and `0x0129`.

Thanks,
Dennis

**Comment by lidel** [comment]
@dennis-tra thank you for noticing that discrepancy! 

This made me notice that in "multihash" section used decimal representation, which was pretty confusing for less technical people ("why sha256 is 18 instead of 12?")

I unified both places (https://github.com/multiformats/cid-utils-website/pull/36/commits/bd7d7186773777cef71cb1009fb444b5cfe388e5) to use  padded hex format present in [`multicodec/table.csv`](https://github.com/multiformats/multicodec/blob/master/table.csv).

Now, codes in multihash and multiformat sections follow exact text format from  'code' column in [`table.csv`](https://github.com/multiformats/multicodec/blob/master/table.csv), which should make it MUCH easier for people to find. 

I also renamed `code` to `prefix` in multibase section just to make clear distinction that it is not related to `multicodec/table.csv`


@jessicaschilling @terichadbourne @zebateira – would appreciate your review 
(this PR impacts onboarding and screenshots in proto.school)

## Preview

> Screenshot_2020-11-02 97910921-c41dba00-1d4a-11eb-86ba-becc364b70d7 png (PNG Image, 593 × 633 pixels)

**Review by lidel — APPROVED** [review]

**Review by jessicaschilling — APPROVED** [review]

**Review by zebateira — APPROVED** [review]
This is great! @terichadbourne noticed this yesterday - thank you for tackling this 🙏

**Comment by lidel** [comment]
Shipped! :tada: 

@jessicaschilling  mind updating screenshot in README of this repo with a pretty mac one?  :pray: 
It still shows decimal codes, which may be confusing.
We want to show codes, so use cidv1, eg. `bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi`

**Comment by jessicaschilling** [comment]
@lidel done!

**Pull request merged**
