### PR TITLE
feat: add fr32-sha2-256-trunc254-padded-binary-tree codec

### PR DESCRIPTION
**Pull request by alanshaw**
refs https://github.com/multiformats/multicodec/pull/331

### CODE REVIEW

**Review by olizilla — APPROVED** [review]
⏩ in b 4 the upstream PR!

**Comment by olizilla** [comment]
@alanshaw plz run `node fetch-tables.js` in this project, so we get the latest multicodecs and then add in `fr32-sha2-256-trunc254-padded-binary-tree codec` so it's less likely to get overwitten while we wait for the multicodec PR to land.

**Comment by alanshaw** [comment]
Oh lol ok!

**Comment by aschmahmann** [comment]
I suspect you're trying to show this off in Iceland which is the reason for the quick merge, which I get. Although it makes me a little uncomfortable that:
1. This is in before the multicodec PR is in
2. This is in before there is consensus on what the format actually is. There are two drafts based on competing requests (https://github.com/filecoin-project/FIPs/pull/758 and https://github.com/filecoin-project/FIPs/pull/808).
    - The first got merged as a pro-forma thing by the managers of the Filecoin FIPs repo with minimal input (basically I proposed and Riba +1'd while Steven, Irakli and Mikeal asked for an alternative which became 808)
    - The second has had some engagement, but no consensus

I'm hoping to get people in a room at FilDev Iceland on Wendesday 9/27 @1:30 PM UTC and get them to decide if the result is 758, 808 or something else which means this in theory is subject to change. 

FYI for anyone looking for that conversation's zoom link you can ask in `#fil-dev-summit` in Filecoin Slack and tag me.

**Comment by olizilla** [comment]
understood. I'm thinking more generally that it would be nice for the cid inspector tool to ahead of "what is confirmed" so it can unpack any cid you might find. The more the merrier... but perhaps with a suitable warning where it determines that a given input is from a PR rather than accepted. 

I'm imagining tweaking this repo to build it's list of codecs from both the table.csv and PRs to it, and labelling PR entries as such, and have a github cron job keep it up to date. Otherwise, I just get pinged when this website fails to decode a hot new cid.

**Pull request merged**
