### PR TITLE
feat: new multiformats

### LINKED ISSUE #40: show multihash for a cid
the `ipfs block` commands work with multihashes rather than CIDs. It would he helpful to be able to paste in a CID and see it's base encoded multihash that could be pasted into one of those commands.

in the meantime you can
```console
$ ipfs --offline cid format -f %m zb2rhe5P4gXftAwvA4eXQ5HJwsER2owDyS9sKaQRRVQPn93bA                                                                                                 
zQmVmkadKS2uvxyD6YJJzd3Umem6SWV7QxYnL7kbpdWAsPS
```

### LINKED ISSUE #43: Can't decode CAR CIDs
There is a multicodec for CARs now. CIDs exist in the wild for them. This site can't decode them yet as it's got an old version of the multicodecs table.

The old ways must give way to the new. [`multicodecs`](https://www.npmjs.com/package/multicodec) is not updated. [`multiformats`](https://github.com/multiformats/js-multiformats) is where the action is.

As suggested by @ribasushi It might be worth reworking this site so that we don't have to redeploy it every time the table is updated. Historical note, it was built this way so that it was self contained, and the site would work entire offline if you have the dag for the site root.

### LINKED ISSUE #44: Can't decode emoji CIDs
Similar problem as #43. IPFS now supports emoji CIDs adn cid.ipfs.io does not.

example from @ribasushi
https://cid.ipfs.io/#🚀🪐⭐💻😅❓💎🌈🌸🌚💰💍🌒😵🐶💁🤐🌎👼🙃🙅☺🌚😞🤤⭐🚀😃✈🌕😚🍻💜🐷⚽✌😊

The main blocker here is that to fix it the guts of the site will have to be rewritten to use the [new multiformats lib](https://github.com/multiformats/js-multiformats/)

### PR DESCRIPTION
**Pull request by hacdias**
- [x] Support for emoji CIDs (closes #44)
- [x] Support for [_any_](https://github.com/multiformats/multicodec/blob/master/table.csv) CIDs (closes #43)
- [x] Show base-encoded multihash (closes #40)
- [x] Update Parcel
	- When [this issue](https://github.com/parcel-bundler/parcel/issues/7854#issuecomment-1179483481) is solved, we can remove the Tachyons patch and use the `errorRecovery` option instead.
- [x] Change Circle CI to GitHub 
	- Circle CI removal tracked in https://github.com/multiformats/cid-utils-website/issues/46 (we don't have permissions)
- [x] support CIDv0
	
image

## After this PR

- Add service worker or some other kind of check to update the multicodec table such that we do not have to always deploy this
- Tests, tests, and more tests.

### CODE REVIEW

**Comment by lidel** [comment]
Based on @olizilla notes in https://github.com/multiformats/cid-utils-website/issues/40 I've tweaked the label of multibase digest, so it is more clear, especially given the base will depend on CID's one:

>

**Review by lidel — APPROVED** [review]
@hacdias thank you! :heart: 
I think we should prioritize shipping this, and move "Perhaps web worker or something to update multiformats table periodically" to a separate issue/PR. I'd rather have CI that updates codecs.json daily than client-side code that sends requests to github.

**Review by lidel — CHANGES_REQUESTED** [review]
@hacdias it seems to [fail with CIDv0: `QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`](https://bafybeibg7swwplxdolhtdaz654tncvqv5wsloq3xxz2fqhfo5tnoa3vybi.on.fleek.co/#QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR) – mind taking a look?

>

**Comment by hacdias** [comment]
@lidel should be fixed

**Review by lidel — APPROVED** [review]
Thanks!

**Comment by lidel** [comment]
@hacdias fyi filled https://github.com/multiformats/cid-utils-website/issues/47 and https://github.com/multiformats/cid-utils-website/issues/48 will potential follow-up tasks (#48 being more important IMO, as it worked before but we had no tests and we broke it :grimacing: )

**Pull request merged**
